CREATE TYPE role_type AS ENUM (
    'USER',
    'ADMIN'
);

CREATE TYPE user_mode AS ENUM (
    'CUTTING',
    'BULKING',
    'MAINTAINING'
);

CREATE TYPE day_of_week AS ENUM (
    'MONDAY',
    'TUESDAY',
    'WEDNESDAY',
    'THURSDAY',
    'FRIDAY',
    'SATURDAY',
    'SUNDAY'
);

CREATE TABLE muscle_group (
     id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name VARCHAR(255) NOT NULL,
     slug VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE role (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name role_type NOT NULL
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    username        VARCHAR(255) NOT NULL UNIQUE,
    password        VARCHAR(255),
    profile_picture VARCHAR(255),
    weight_goal     DOUBLE PRECISION,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    mode            user_mode
);

CREATE TABLE exercise (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255) NOT NULL,
    slug            VARCHAR(255) NOT NULL UNIQUE,
    description     TEXT,
    video_how_to    VARCHAR(255),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    muscle_group_id BIGINT NOT NULL REFERENCES muscle_group,
    submitter_id    BIGINT NOT NULL REFERENCES users
);

CREATE TABLE refresh_token (
    id          UUID PRIMARY KEY,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    expires_at  TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    user_id     BIGINT REFERENCES users
);

CREATE TABLE user_roles (
    role_id BIGINT NOT NULL REFERENCES role,
    user_id BIGINT NOT NULL REFERENCES users,
    PRIMARY KEY (role_id, user_id)
);

CREATE TABLE weight (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kg         DOUBLE PRECISION,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    user_id    BIGINT REFERENCES users
);

CREATE TABLE workout (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note       TEXT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    user_id    BIGINT REFERENCES users
);

CREATE TABLE workout_exercise (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workout_id  BIGINT REFERENCES workout,
    exercise_id BIGINT NOT NULL REFERENCES exercise
);

CREATE TABLE exercise_set (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kg                  DOUBLE PRECISION NOT NULL,
    reps                BIGINT NOT NULL,
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    updated_at          TIMESTAMP(6) WITH TIME ZONE,
    workout_exercise_id BIGINT REFERENCES workout_exercise
);

CREATE TABLE workout_plan (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    user_id     BIGINT REFERENCES users
);

CREATE TABLE routine (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL,
    note                  TEXT,
    workout_plan_id       BIGINT REFERENCES workout_plan,
    desirable_day_of_week day_of_week NOT NULL
);

CREATE TABLE routine_exercise (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    desirable_reps BIGINT NOT NULL,
    desirable_sets BIGINT NOT NULL,
    routine_id     BIGINT REFERENCES routine,
    exercise_id    BIGINT NOT NULL REFERENCES exercise
);