DROP TYPE IF EXISTS nutrient_type;

CREATE TYPE nutrient_type AS ENUM (
    'PROTEIN',
    'CARBOHYDRATE',
    'FAT'
);

CREATE TABLE meal (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    kcal DOUBLE PRECISION                        NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    CONSTRAINT pk_meal PRIMARY KEY (id)
);

CREATE TABLE macronutrient (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nutrient nutrient_type                           NOT NULL,
    grams    DOUBLE PRECISION                        NOT NULL,
    meal_id  BIGINT,
    CONSTRAINT pk_macronutrient PRIMARY KEY (id)
);

ALTER TABLE macronutrient
    ADD CONSTRAINT FK_MACRONUTRIENT_ON_MEAL FOREIGN KEY (meal_id) REFERENCES meal (id);