server:
  forward-headers-strategy: framework

spring:
  datasource:
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    show-sql: false
  flyway:
      locations: classpath:db/migration
authentication:
  token:
    jwt:
      private-key: file:${JWT_PRIVATE_KEY_PATH}
      public-key: file:${JWT_PUBLIC_KEY_PATH}

client:
  domain: ${CLIENT_DOMAIN}
  oauth2RedirectAfter: ${CLIENT_OAUTH2_REDIRECT_AFTER}

storage:
  current-provider: R2
  multipart-max-file-size: ${spring.servlet.multipart.max-file-size}
  local:
    directory: ${STORAGE_LOCAL_IMAGE_DIRECTORY}
  r2:
    endpoint: ${STORAGE_R2_ENDPOINT}
    access-key: ${STORAGE_R2_ACCESS_KEY}
    secret-key: ${STORAGE_R2_SECRET_KEY}
    bucket: ${STORAGE_R2_BUCKET}