spring:
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration, classpath:db/testdata
  datasource:
    username: postgres
    password: admin
    url: jdbc:postgresql://localhost:5432/gymniac

authentication:
  token:
    jwt:
      private-key: classpath:private.pem
      public-key: classpath:public.pem

client:
  domain: localhost
  oauth2RedirectAfter: http://localhost:3000/login/google/success